# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 12:26
from __future__ import unicode_literals

import cvr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvr', '0002_auto_20170308_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=cvr.models.user_image_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, upload_to=cvr.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='free_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
