# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvr', '0004_profile_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_privledged',
            field=models.BooleanField(default=False),
        ),
    ]
