# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvr', '0005_profile_is_privledged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='approved',
            new_name='is_approved',
        ),
        migrations.AlterField(
            model_name='profile',
            name='free_text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
